<?php

use Drupal\Component\Utility\NestedArray;

/**
 * Run the body class context reactions if there are any and let them add
 * classes to the page body.
 *
 * Implements hook_preprocess_HOOK().
 */
function context_preprocess_html(&$variables) {
  /** @var \Drupal\context\ContextManager $context_manager */
  $context_manager = \Drupal::service('context.manager');

  foreach ($context_manager->getActiveReactions('body_class') as $reaction) {
    $variables['attributes'] = NestedArray::mergeDeep($variables['attributes'], $reaction->execute());
  }
}
